#!/bin/bash

#
# Simple script to create dir layout for new htb box and to do an initial scan on it's ip
#
# Usage: ./new_box {box name} {box IP}
#
# By flatwhite
#

if [ $# != 2 ]; then

	echo "[?] Incorrect number of args."
	echo "[-] Usage: $0 {box name} {box IP}"

else

	boxName=$1
	boxIP=$2

	if ! ping -c 1 $boxIP &> /dev/null; then
		echo "[?] $boxName ($boxIP) isn't reachable. Are you sure it's up?"
		exit
	fi

	clear
	echo "[+] Starting setup..."
	sleep 1
	clear

	echo "[+] Creating directories"
	mkdir "$boxName"
	mkdir "$boxName/1_scans"
	mkdir "$boxName/2_foothold"
	mkdir "$boxName/3_user"
	mkdir "$boxName/4_root"

	echo "[+] Creating IP reminder file"
	touch "$boxName/0_$boxIP"

	echo "[+] Creating notes file"
	touch "$boxName/notes.txt"

	echo "[+] Creating nc listener script"
	echo "nc -lvnp 9001" > "$boxName/listener.sh"
	chmod +x "$boxName/listener.sh"

	echo "[+] Starting nmap scan"

	xfce4-terminal -e "bash -c 'sudo nmap -v -sV -sS -O -p- -T4 -sC -oN $boxName/1_scans/nmap.txt $boxIP'" -T "Nmap on $boxName" &

	if nc $boxIP 80 -z -w 3 &> /dev/null ; then

		echo ""
		echo "[!] Detected web service!"
		echo "[+] Starting gobuster..."
		xfce4-terminal -e "bash -c '~/go/bin/gobuster dir -u $boxIP -w /usr/share/wordlists/dirbuster/directory-list-2.3-medium.txt -o $boxName/1_scans/gobuster.txt'" -T "Gobuster on $boxName" &


		echo "[+] Opening firefox at http://$boxIP (so you can do something while the scans are running)"
		firefox $boxIP &

	fi


	echo ""
	echo "[+] Everything setup and scanned! Follow the white rabbit, $USER..."
	echo ""

	cd $boxName

fi
